version: '3.9'

services:
  db:
    image: postgres:14.1
    container_name: container_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "shareit"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "iamroot"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  web:
    image: server_image
    container_name: server_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8183:8183"
    depends_on:
      - db
    environment:
      - SERVER_PORT= 8183
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/shareit