version: '3.8'

services:
  db:
    image: postgres:13.7-alpine
    container_name: container_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  web:
    build: .
    image: server_image
    container_name: server_container
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_NAME=shareit
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
      - DB_HOST=db
      - DB_PORT=5432